Optimize single & batch query response writers to reduce memory allocation overhead
graphql-java-kickstart/graphql-java-servlet pull request #292
Opened 2020-12-29 20:06 UTC by artem-ag

Optimize single & batch query response writers to reduce memory allocation overhead caused by the servlet.

When large 10MiB+ responses are serialized, existing implementation performs significant amount of redundant string conversions and string concatenations. In my scenario overhead reached as much as 4GiB in extra RAM allocated.

This change replaces Json serialization into a String with Json serialization into byte array for both single and batch queries. In addition, it removes all string concatenations from batch response writer.

2020-12-30 07:43 UTC, oliemansm requested changes
JDK8 based tests are failing, can you take a look at that? Maybe you're using something not compatible with JDK8?

Can you also try to get >80% test coverage on your changes? I see you have added tests, but can't judge coverage, and unfortunately SonarCloud doesn't support PR analysis on external PRs yet.

2020-12-31 03:17 UTC, artem-ag commented
> JDK8 based tests are failing, can you take a look at that? Maybe you're using something not compatible with JDK8?
> 
> Can you also try to get >80% test coverage on your changes? I see you have added tests, but can't judge coverage, and unfortunately SonarCloud doesn't support PR analysis on external PRs yet.

Didn't realize 8, 11, 15 are jdk version numbers... Updated test to be backward compatible. PTAL.

The new class has close to 100% coverage:
<img width="831" alt="Screen Shot 2020-12-30 at 7 13 59 PM" src="https://user-images.githubusercontent.com/65827946/103392580-723bab00-4ad3-11eb-8ec0-8d2752c81e20.png">

2020-12-31 13:43 UTC, oliemansm approved these changes

2020-12-31 13:43 UTC, merged

2020-12-31 13:43 UTC, oliemansm commented
Thanks a lot!